# **BIT611 Machine Learning**
## Laboratory One Assessment

**Objective**
- Apply a basic data preprocessing workflow using Python. You will load a public dataset, inspect it, handle missing values using fixed rules, encode categorical variables, scale numeric variables, and create a train/test split ready for machine learning.

**Dataset** 
- raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

### Part A - Load and Inspect the Dataset

1) Load the Titanic Dataset into a Pandas DataFrame

In [1]:
#Import
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

#Try-Catch To Catch Exceptions
try:
    df = pd.read_csv(url)
    print('Loaded dataset from:', url)
except Exception as e:
    print('Failed:', url, '|', repr(e))

Loaded dataset from: https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

2) Show:
    - First 5 Rows
    - Shape
    - Column Names
    - Data Types

In [2]:
#Shows First 5 Rows
print("First 5 Rows")
df.head()

First 5 Rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
#Shows Shape
print("\nShape of Dataset:")
print(df.shape)

#Shows Columns
print("\nColumn Names:")
print(list(df.columns))

#Shows Data Type
print("\nData Types:")
print(df.dtypes)

Shape of Dataset:
(891, 12)

Column Names:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

Data Types:
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

3) Identify Which Columns Are:
- Numeric
- Categorical
- Contain Missing values

**Required Output:** 
- A Short Table Showing Missing Value Counts per Column

In [4]:
#Separates By Data Type
numeric_cols = df.select_dtypes(include='number').columns
categorical_cols = df.select_dtypes(include=['object', 'string']).columns

#Shows Numeric Columns
print("Numeric columns:")
print(list(numeric_cols))

#Shows Catergorical Columns
print("\nCategorical columns:")
print(list(categorical_cols))

Numeric columns:
['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

Categorical columns:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [5]:
#Shows Missing Values
print("Missing values per column:")
df.isnull().sum().to_frame("Missing Values")

Missing values per column:

             Missing Values
PassengerId               0
Survived                  0
Pclass                    0
Name                      0
Sex                       0
Age                     177
SibSp                     0
Parch                     0
Ticket                    0
Fare                      0
Cabin                   687
Embarked                  2

### Part B - Handle Missing Values

Handle Missing Values Using the Following Rules:
1) **Age:** Fill Missing Values with the Median Age
2) **Embarked:** Fill Missing Values with the Most Frequent Value
3) **Drop Columns:** Remove Cabin

**Required Output:**
- Missing Value Counts Before and After
- A Brief Note Explaining What I Did

In [6]:
#Shows Missing Values
print("Missing Values BEFORE Handling")
df.isnull().sum().to_frame("Missing Values")

Missing Values BEFORE Handling

             Missing Values
PassengerId               0
Survived                  0
Pclass                    0
Name                      0
Sex                       0
Age                     177
SibSp                     0
Parch                     0
Ticket                    0
Fare                      0
Cabin                   687
Embarked                  2

In [7]:
# Fill Age with median
df['Age'] = df['Age'].fillna(df['Age'].median())

# Fill Embarked with mode
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Drop Cabin
df = df.drop(columns=['Cabin'], errors='ignore')

In [8]:
#Shows Missing Values
print("\nMissing Values AFTER Handling")
df.isnull().sum().to_frame("Missing Values")

Missing Values AFTER Handling

             Missing Values
PassengerId               0
Survived                  0
Pclass                    0
Name                      0
Sex                       0
Age                       0
SibSp                     0
Parch                     0
Ticket                    0
Fare                      0
Embarked                  0

**Required Written Note**
- Missing values in the Age column were changed using the median value to reduce outliers
- Missing values in the Embarked column were replaced using mode filling them with the most frequent values
- The Cabin column was removed as it contained a large portion of missing values and would not be relevant for modelling

### Part C - Encode Categorical Variables
1) Select These Categorical Columns:
    - Sex
    - Embarked
2) Apply One-Hot Encoding

**Required Output**
- List of Final Feature Column Names After Encoding
- Show the First 5 Rows of the Encoded Dataset

In [9]:
#Encodes Sex and Embarked
df_encoded = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

df_encoded.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Sex_male,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,True,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,False,False,True
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,True,False,True

In [10]:
#Shows Columns
print("Final feature column names:")
print(list(df_encoded.columns))

Final feature column names:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Sex_male', 'Embarked_Q', 'Embarked_S']

### Part D - Scale Numeric Variables

Scale These Numeric Columns Using StandardScaler:
- Age
- Fare

**Required Output:**
- Show Summary Statistics for Age and Fare Before Scaling
- Show Summary Statistics After Scaling

In [11]:
#Import
from sklearn.preprocessing import StandardScaler

#Shows Age and Fare
print("Before Scaling:")
print(df_encoded[['Age', 'Fare']].describe())

Before Scaling:
              Age        Fare
count  891.000000  891.000000
mean    29.361582   32.204208
std     13.019697   49.693429
min      0.420000    0.000000
25%     22.000000    7.910400
50%     28.000000   14.454200
75%     35.000000   31.000000
max     80.000000  512.329200

In [12]:
#Scales
scaler = StandardScaler()
df_encoded[['Age', 'Fare']] = scaler.fit_transform(df_encoded[['Age', 'Fare']])

#Shows Age and Fare
print("After Scaling:")
print(df_encoded[['Age', 'Fare']].describe())

After Scaling:
                Age          Fare
count  8.910000e+02  8.910000e+02
mean   2.272780e-16  3.987333e-18
std    1.000562e+00  1.000562e+00
min   -2.224156e+00 -6.484217e-01
25%   -5.657365e-01 -4.891482e-01
50%   -1.046374e-01 -3.573909e-01
75%    4.333115e-01 -2.424635e-02
max    3.891554e+00  9.667167e+00

### Part E - Train/Test Split
Split the Dataset into 80% Train / 20% Test Using:
- random_state = 42

Use:
- X = All Processed Feature Columns
- y = Survived

**Required Output:**

Print Shapes of:
- X_train, X_test, y_train, y_test

In [13]:
#Train/TEst Split into 80/20
X = df_encoded.drop('Survived', axis=1)
y = df_encoded['Survived']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
    )

#Shows Results
print(f"X_train shape: ({X_train.shape[0]}, {X_train.shape[1]})")
print(f"X_test shape: ({X_test.shape[0]}, {X_test.shape[1]})")
print(f"y_train shape: ({y_train.shape[0]})")
print(f"y_test shape: ({y_test.shape[0]})")

X_train shape: (712, 11)
X_test shape: (179, 11)
y_train shape: (712)
y_test shape: (179)